"""Add Plaid models - bank accounts, transactions, categories

Revision ID: cd6d8adfce4a
Revises: 68b324aa3d62
Create Date: 2025-12-23 16:47:03.087454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6d8adfce4a'
down_revision: Union[str, None] = '68b324aa3d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_access_token', sa.String(length=500), nullable=False),
    sa.Column('plaid_cursor', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('include_in_budget', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.String(length=500), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_accounts_plaid_account_id'), 'bank_accounts', ['plaid_account_id'], unique=True)
    op.create_index(op.f('ix_bank_accounts_plaid_item_id'), 'bank_accounts', ['plaid_item_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='categorytype'), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('household_id', sa.UUID(), nullable=False),
    sa.Column('plaid_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('authorized_date', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('plaid_category', sa.String(length=255), nullable=True),
    sa.Column('plaid_category_id', sa.String(length=50), nullable=True),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('payment_meta', sa.Text(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['bank_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_account_date', 'transactions', ['account_id', 'date'], unique=False)
    op.create_index('idx_transaction_category', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_transaction_household_date', 'transactions', ['household_id', 'date'], unique=False)
    op.create_index(op.f('ix_transactions_plaid_transaction_id'), 'transactions', ['plaid_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_plaid_transaction_id'), table_name='transactions')
    op.drop_index('idx_transaction_household_date', table_name='transactions')
    op.drop_index('idx_transaction_category', table_name='transactions')
    op.drop_index('idx_transaction_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('categories')
    op.drop_index(op.f('ix_bank_accounts_plaid_item_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_plaid_account_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    # ### end Alembic commands ###
